deploy: android - fix order jobs

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -222,18 +222,28 @@ jobs:
           FIREBASE_ANDROID_APP_ID: ${{ secrets.FIREBASE_ANDROID_APP_ID }}
           FIREBASE_IOS_APP_ID: ${{ secrets.FIREBASE_IOS_APP_ID }}
         run: |
+          set -ex
           MSG="${{ needs.prepare.outputs.message }}"
+          echo "Deploy message: $MSG"
+
           if echo "$MSG" | grep -q "android"; then
             cd android
             bundle config set --local path vendor/bundle
             bundle install --jobs 4 --retry 3
             bundle exec fastlane android deploy environment:dev --verbose
+            cd -
+          else
+            echo "Skip Android deploy: message missing 'android'"
           fi
+
           if echo "$MSG" | grep -q "ios"; then
             cd ios
             bundle config set --local path vendor/bundle
             bundle install --jobs 4 --retry 3
             bundle exec fastlane ios deploy environment:dev --verbose
+            cd -
+          else
+            echo "Skip iOS deploy: message missing 'ios'"
           fi
 
   # ============= STAGING =============
